### ISSUE TITLE
No such file or directory: '/home/nugrinovic/datasets/prox/qualitative/calibration/Color.json'

### ISSUE THREAD

**Issue by PolarisXQ** [nicolasugrinovic/multiphys#1]
```bash
No such file or directory: '/home/nugrinovic/datasets/prox/qualitative/calibration/Color.json'
```
Where can I find these files?

**Comment by nicolasugrinovic** [comment]
Hi, you need to download camera data from[ PROX dataset](https://prox.is.tue.mpg.de/) which is only to initialize the system, place it in any location, e.g., ./datasets/prox/, change the path directory, and re-run the script.

**Comment by PolarisXQ** [comment]
Thanks for your great work and reply!
Problem solved!
