### ISSUE TITLE
I am a beginner. What does the following list represent?

### ISSUE THREAD

**Issue by laoniandisko** [nicolasugrinovic/multiphys#3]
['acro1_a-frame1_cam20', 'acro1_a-frame1_cam30', 'acro1_around-the-back1_cam20', 'acro1_around-the-back1_cam30', 'acro1_back-flip1_cam20', 'acro1_back-flip1_cam30', 'acro1_big-ben1_cam20', 'acro1_big-ben1_cam30', 'acro1_cartwheel3_cam20', 'acro1_cartwheel3_cam30', 'acro1_chandelle3_cam20', 'acro1_chandelle3_cam30', 'acro1_check-the-change1_cam20', 'acro1_check-the-change1_cam30', 'acro1_coochie1_cam20', 'acro1_coochie1_cam30', 'acro1_frog-classic1_cam20', 'acro1_frog-classic1_cam30', 'acro1_frog-turn1_cam20', 'acro1_frog-turn1_cam30', 'acro1_toss-out1_cam20', 'acro1_toss-out1_cam30', 'acro1_twisted-toss1_cam20', 'acro1_twisted-toss1_cam30']

**Comment by nicolasugrinovic** [comment]
Those are the sequence names for ExPI datasets together with their respective cameras. So you have "sequenceName_cameraNumber". For this dataset we use only two cameras per actor pair.

**Comment by laoniandisko** [comment]
> Those are the sequence names for ExPI datasets together with their respective cameras. So you have "sequenceName_cameraNumber". For this dataset we use only two cameras per actor pair.

How can I use my own video for inference?

**Comment by nicolasugrinovic** [comment]
You need to generate your own initial data file, following the same format as, e.g, the file `sample_data/expi/expi_acro1_p1_phalpBox_all_slaInit_slaCam.pkl`. This includes detecting the 2d keypoints with ViTPose and running [SLAHRM](https://github.com/vye16/slahmr) to get the initial 3D body pose and camera estimates. 

I will soon push the script used to generate this file from the initial ViTPose and SLAHMR results.

**Comment by laoniandisko** [comment]
\

> You need to generate your own initial data file, following the same format as, e.g, the file `sample_data/expi/expi_acro1_p1_phalpBox_all_slaInit_slaCam.pkl`. This includes detecting the 2d keypoints with ViTPose and running [SLAHRM](https://github.com/vye16/slahmr) to get the initial 3D body pose and camera estimates.
> 
> I will soon push the script used to generate this file from the initial ViTPose and SLAHMR results.

Thank you for your reply, I am very much looking forward to your work.
