### ISSUE TITLE
Policy Learning

### ISSUE THREAD

**Issue by IDayday** [nicolasugrinovic/multiphys#4]
Hi, I'm very interested in the full implementation of this work.
At present, I have seen that the project has released the policy network weights, but how to train the policy is still unknown? More specifically, how to implement the imitation learning described in the paper? I am very curious about this.

**Comment by nicolasugrinovic** [comment]
Hi, thanks for your interest in our work. 

For the policy network, we use the [UHC](https://github.com/ZhengyiLuo/UHC) using the same weights provided by the authors with a slight modification that does not require re-training. Please take a look at the original repo and paper for the training procedure and formulation.

**Comment by IDayday** [comment]
OK, thanks for your answer
